### ISSUE TITLE
Running with default config doesn't seem to have "writing" page/section 

### ISSUE THREAD

**Issue by DasithKuruppu** [EmaSuriano/gatsby-starter-mate#38] opened 2019-04-01 22:47 UTC
![tesa](https://user-images.githubusercontent.com/7686931/55364488-6ede4e80-54fe-11e9-848d-98b660635ec7.PNG)

Any idea how to add the writing page or fix it?

**Comment by EmaSuriano** [comment] 2019-04-02 08:11
Hey!
As I don't have access to your contentful space I can't be really specific with my answer but I think I know the problem you're tackling right now. 

There is one technical decision I made when I designed the contentful entities and their relations and is that your `About` Content is the single source of truth for your application. Therefore everything that is connected to it will be available inside your application (you can check the GraphQL queries for that). 

One problem I had in the past, was to create a new `Project` or `Social Link` and never linked them with my `About` content. To check this part, go to your `About` content and check if all your projects are properly linked with it. 

Let me know if this was your problem. Otherwise, I will need a few more details 😅

**Comment by DasithKuruppu** [comment] 2019-04-03 08:13
Ohh thanks for the quick reply , haven't had the chance to go through it yet. Will let you know as soon as I try your suggestion out. 👍

**Comment by seanjun21** [comment] 2019-04-05 06:43
Hi guys, I'm actually having a similar problem. Was there a resolution to this? It looks like the variable `isMediumUserDefine` is considered `null` when I ran locally.

**Comment by EmaSuriano** [comment] 2019-04-05 12:56
Hello there 👋 In case the `isMediumUserDefine` is null is because you didn't define your Medium User inside your `About` entity inside Contentful. The query I'm running to check it is this one:

``` graphql
isMediumUserDefine: __type(
  name: "contentfulAboutMediumUserQueryString_2"
) {
  name
}
```

Please check if you have defined its value like I'm doing for the starter 😄
![image](https://user-images.githubusercontent.com/3399429/55629102-a117d680-57b2-11e9-9557-97d659b3fc85.png)

Hope this solve your issue! In case, this doesn't solve your problem I migth need to have access to your Contentful space.

**Comment by seanjun21** [comment] 2019-04-05 18:17
@EmaSuriano that's weird because I have it already set like that and it was working before (roughly 2-3 months ago?)
Yesterday, I pulled the latest updates from the original repo and writing section just disappeared.

**Comment by EmaSuriano** [comment] 2019-04-09 08:29
Mmmm it's weird, this is the first time I hear something like that. You can always clone the repo from scratch and point to your same Contentful space, and check if it works.

In the past releases, I try not to change the schema of the data and only change the code inside the project, so you won't lose any data in this process 😄

Try that and in case it doesn't work we can do a short call and see the problem closer.

**Comment by seanjun21** [comment] 2019-04-09 17:00
@EmaSuriano I will try that and give you feedback (it should work in theory).
By the way, I had another request (more like a feature request) that I wanted to ask.
I will create another issue and address it there.

**Comment by seanjun21** [comment] 2019-04-09 18:10
@EmaSuriano I did what you said, and it's still not showing the writing section. Maybe the problem is coming from Netlify? I'm going to try to debug this and let you know what I can find.

**Comment by EmaSuriano** [comment] 2019-04-09 18:13
Maybe it's a silly answer, but did you trigger again a build? 😅

**Comment by seanjun21** [comment] 2019-04-09 18:40
@EmaSuriano Alright, so I hard reset the repository again and this time it worked. Thanks for the help 👍 If anyone's having this issue, I'm thinking it's probably the best idea to reset hard from the original repository.

**Comment by EmaSuriano** [comment] 2019-04-10 12:52
@seanjun21  glad it works with a little bit of clean up 🎉
@DasithKuruppu did you manage to fix your page? I would love to close this issue 😄

**Comment by DasithKuruppu** [comment] 2019-04-17 06:45
@EmaSuriano still unable to fix it , but will try and give it another go as @seanjun21 suggested and update you within the next 2 days

**Comment by jonbiro** [comment] 2019-04-29 18:17
The problem I found is that if you update any of the node packages; like to the newest version of gatsby or react, the writing section stops showing up. @EmaSuriano, any idea of how to fix it?

**Comment by spaghetticodebonara** [comment] 2019-05-01 16:32
Hi Guys! I had the same problem on my Contentful profile. To show Writing section I modified **Writing.js** file
from:
```
const Writing = () => (
  <StaticQuery
    query={graphql`
      query MediumPostQuery {
        isMediumUserDefine: __type(
          name: "contentfulAboutMediumUserQueryString_2"
        ) {
          name
        }
```
to: 
```
const Writing = () => (
  <StaticQuery
    query={graphql`
      query MediumPostQuery {
        isMediumUserDefine: allMediumUser{
          nodes {
            username
          }
        }
```

**Comment by jonbiro** [comment] 2019-05-01 23:44
@spaghetticodebonara That gives me an error about 'nodes' not being defined. I fixed it by getting rid of the isMediumUserDefine.

Here are the latest packages available for your package.json:

  "dependencies": {
    "clean-dir": "^1.0.3",
    "contentful": "^7.5.0",
    "dotenv": "^7.0.0",
    "envfile": "^3.0.0",
    "gatsby": "^2.3.35",
    "gatsby-plugin-google-analytics": "^2.0.19",
    "gatsby-plugin-google-fonts": "^0.0.4",
    "gatsby-plugin-manifest": "^2.0.29",
    "gatsby-plugin-offline": "^2.0.25",
    "gatsby-plugin-react-helmet": "^3.0.12",
    "gatsby-plugin-styled-components": "^3.0.7",
    "gatsby-source-contentful": "^2.0.54",
    "gatsby-source-medium": "^2.0.7",
    "gatsby-transformer-remark": "^2.3.12",
    "inquirer": "^6.3.1",
    "prop-types": "^15.7.2",
    "react": "^16.8.6",
    "react-dom": "^16.8.6",
    "react-fontawesome": "^1.6.1",
    "react-headroom": "^2.2.8",
    "react-helmet": "^5.2.1",
    "react-markdown": "^4.0.8",
    "react-reveal": "^1.2.2",
    "react-scroll-section": "^1.3.0",
    "react-text-loop": "^2.0.1",
    "react-tippy": "^1.2.3",
    "rebass": "^3.1.0",
    "styled-components": "^4.2.0"
  },
  "devDependencies": {
    "chalk": "^2.4.2",
    "contentful-import": "^7.4.4",
    "eslint": "^5.16.0",
    "eslint-config-airbnb": "^17.1.0",
    "eslint-config-prettier": "^4.2.0",
    "eslint-plugin-import": "^2.17.2",
    "eslint-plugin-jsx-a11y": "^6.2.1",
    "eslint-plugin-react": "^7.12.4",
    "husky": "^2.1.0",
    "lint-staged": "^8.1.5"

**Comment by EmaSuriano** [comment] 2019-05-02 16:08
Hello guys, so I've been playing around with it and I didn't like at all how I was checking for the mediumUser (I was using some internal value from Contentful, which can change depending on who knows and they strongly insist on not using it). Therefore I came with another solution, much cleaner and without any "black magic", which is pushing the value of `isMediumDefined` from the `gatsby-config.json` using the `siteMetadata`. 
You can check the changes in [this pr](https://github.com/EmaSuriano/gatsby-starter-mate/pull/47). 
Please update your starter and let me know if now is working for all you! 🙏

**Comment by jonbiro** [comment] 2019-05-06 19:37
Yeah it works! You can close this issue!

**Closed** 2019-05-06 19:48 UTC
