### ISSUE TITLE
npm start - failed extract queries from components 

### ISSUE THREAD

**Issue by fongaloid** [EmaSuriano/gatsby-starter-mate#79] opened 2019-12-10 08:23 UTC
I'm getting a bunch of errors after installing fresh, any ideas?

```
> npm start

> gatsby-starter-mate@2.5.2 start /Users/sfong/Projects/mate-portfolio
> npm run develop


> gatsby-starter-mate@2.5.2 develop /Users/sfong/Projects/mate-portfolio
> gatsby clean && gatsby develop

info Deleting .cache, public
info Successfully deleted directories
success open and validate gatsby-configs - 0.044s
success load plugins - 0.105s
success onPreInit - 0.002s
success initialize cache - 0.010s
success copy gatsby files - 0.047s
success onPreBootstrap - 0.010s
success createSchemaCustomization - 0.002s
success source and transform nodes - 0.037s
success building schema - 0.178s
success createPages - 0.002s
success createPagesStatefully - 0.065s
success onPreExtractQueries - 0.002s
success update schema - 0.017s

 ERROR #85901  GRAPHQL

There was an error in your GraphQL query:

Unknown type "ContentfulFixed".

File: node_modules/gatsby-source-contentful/src/fragments.js:20:37


 ERROR #85901  GRAPHQL

There was an error in your GraphQL query:

Unknown type "ContentfulFixed".

File: node_modules/gatsby-source-contentful/src/fragments.js:34:47


 ERROR #85901  GRAPHQL

There was an error in your GraphQL query:

Unknown type "ContentfulFixed".

File: node_modules/gatsby-source-contentful/src/fragments.js:48:46


 ERROR #85901  GRAPHQL

There was an error in your GraphQL query:

Unknown type "ContentfulFixed".

File: node_modules/gatsby-source-contentful/src/fragments.js:61:46


 ERROR #85901  GRAPHQL

There was an error in your GraphQL query:

Unknown type "ContentfulFixed".

File: node_modules/gatsby-source-contentful/src/fragments.js:77:55


 ERROR #85901  GRAPHQL

There was an error in your GraphQL query:

Unknown type "ContentfulFluid".

File: node_modules/gatsby-source-contentful/src/fragments.js:92:37


 ERROR #85901  GRAPHQL

There was an error in your GraphQL query:

Unknown type "ContentfulFluid".

File: node_modules/gatsby-source-contentful/src/fragments.js:106:47


 ERROR #85901  GRAPHQL

There was an error in your GraphQL query:

Unknown type "ContentfulFluid".

File: node_modules/gatsby-source-contentful/src/fragments.js:120:46


 ERROR #85901  GRAPHQL

There was an error in your GraphQL query:

Unknown type "ContentfulFluid".

File: node_modules/gatsby-source-contentful/src/fragments.js:133:46


 ERROR #85901  GRAPHQL

There was an error in your GraphQL query:

Unknown type "ContentfulFluid".

File: node_modules/gatsby-source-contentful/src/fragments.js:149:55


 ERROR #85901  GRAPHQL

There was an error in your GraphQL query:

Unknown type "ContentfulResolutions".

File: node_modules/gatsby-source-contentful/src/fragments.js:161:43


 ERROR #85901  GRAPHQL

There was an error in your GraphQL query:

Unknown type "ContentfulResolutions".

File: node_modules/gatsby-source-contentful/src/fragments.js:171:53


 ERROR #85901  GRAPHQL

There was an error in your GraphQL query:

Unknown type "ContentfulResolutions".

File: node_modules/gatsby-source-contentful/src/fragments.js:181:52


 ERROR #85901  GRAPHQL

There was an error in your GraphQL query:

Unknown type "ContentfulResolutions".

File: node_modules/gatsby-source-contentful/src/fragments.js:190:52


 ERROR #85901  GRAPHQL

There was an error in your GraphQL query:

Unknown type "ContentfulResolutions".

File: node_modules/gatsby-source-contentful/src/fragments.js:202:61


 ERROR #85901  GRAPHQL

There was an error in your GraphQL query:

Unknown type "ContentfulSizes".

File: node_modules/gatsby-source-contentful/src/fragments.js:213:37


 ERROR #85901  GRAPHQL

There was an error in your GraphQL query:

Unknown type "ContentfulSizes".

File: node_modules/gatsby-source-contentful/src/fragments.js:223:47


 ERROR #85901  GRAPHQL

There was an error in your GraphQL query:

Unknown type "ContentfulSizes".

File: node_modules/gatsby-source-contentful/src/fragments.js:233:46


 ERROR #85901  GRAPHQL

There was an error in your GraphQL query:

Unknown type "ContentfulSizes".

File: node_modules/gatsby-source-contentful/src/fragments.js:242:46


 ERROR #85901  GRAPHQL

There was an error in your GraphQL query:

Unknown type "ContentfulSizes".

File: node_modules/gatsby-source-contentful/src/fragments.js:254:55


 ERROR #85901  GRAPHQL

There was an error in your GraphQL query:

Cannot query field "contentfulAbout" on type "Query".

GraphQL request:3:9
2 |       query FooterQuery {
3 |         contentfulAbout {
  |         ^
4 |           name

File: src/components/Footer.js:31:9


 ERROR #85901  GRAPHQL

There was an error in your GraphQL query:

Cannot query field "contentfulAbout" on type "Query".

GraphQL request:3:9
2 |       query HelmetQuery {
3 |         contentfulAbout {
  |         ^
4 |           name

File: src/components/Helmet.js:11:9


 ERROR #85901  GRAPHQL

There was an error in your GraphQL query:

Cannot query field "contentfulAbout" on type "Query".

GraphQL request:3:11
2 |         query AboutMeQuery {
3 |           contentfulAbout {
  |           ^
4 |             aboutMe {

File: src/sections/About.js:50:11


 ERROR #85901  GRAPHQL

There was an error in your GraphQL query:

Cannot query field "contentfulAbout" on type "Query".

GraphQL request:3:11
2 |         query SiteTitleQuery {
3 |           contentfulAbout {
  |           ^
4 |             name

File: src/sections/Landing.js:49:11


 ERROR #85901  GRAPHQL

There was an error in your GraphQL query:

Cannot query field "siteMetadata" on type "Site".

GraphQL request:14:13
13 |           site {
14 |             siteMetadata {
   |             ^
15 |               deterministicBehaviour

File: src/sections/Landing.js:60:13


 ERROR #85901  GRAPHQL

There was an error in your GraphQL query:

Cannot query field "contentfulAbout" on type "Query".

GraphQL request:3:11
2 |         query ProjectsQuery {
3 |           contentfulAbout {
  |           ^
4 |             projects {

File: src/sections/Projects.js:184:11


 ERROR #85901  GRAPHQL

There was an error in your GraphQL query:

Cannot query field "siteMetadata" on type "Site".

GraphQL request:4:11
3 |         site {
4 |           siteMetadata {
  |           ^
5 |             isMediumUserDefined

File: src/sections/Writing.js:140:11


 ERROR #85901  GRAPHQL

There was an error in your GraphQL query:

Cannot query field "allMediumPost" on type "Query".

GraphQL request:8:9
7 |         }
8 |         allMediumPost(limit: 7, sort: { fields: createdAt, order: DESC }) {
  |         ^
9 |           totalCount

File: src/sections/Writing.js:144:9


 ERROR #85901  GRAPHQL

There was an error in your GraphQL query:

Cannot query field "mediumUser" on type "Query".

GraphQL request:26:9
25 |         }
26 |         author: mediumUser {
   |         ^
27 |           username

File: src/sections/Writing.js:162:9

failed extract queries from components - 1.003s
success write out requires - 0.044s
success write out redirect data - 0.003s
success onPostBootstrap - 0.002s
⠀
info bootstrap finished - 5.155 s
⠀
success run queries - 0.025s - 4/4 158.50/s
⠀
You can now view gatsby-starter-mate in the browser.
⠀
  http://localhost:8000/
⠀
View GraphiQL, an in-browser IDE, to explore your site's data and schema
⠀
  http://localhost:8000/___graphql
⠀
Note that the development build is not optimized.
To create a production build, use gatsby build
⠀
success Building development bundle - 3.471s


————————————————————————————————————————————————————————————————————————————————
4 pages                        Failed                        gatsby-starter-mate
```

**Comment by fongaloid** [comment] 2019-12-10 11:22
I got it to work by cloning the repo `git clone https://github.com/EmaSuriano/gatsby-starter-mate.git mate-portfolio` and then running `npm install` followed by `npm  run setup` and finally `npm start`.

running `$ gatsby new mate-portfolio https://github.com/EmaSuriano/gatsby-starter-mate` did not seem to work and the 'package-lock.json' was not present.

**Comment by EmaSuriano** [comment] 2019-12-15 21:06
Hey @fongaloid, as you said the `gatsby-cli` was not cloning the `package-lock.json` when running `gatsby new`. This is because it's set by default as `yarn` --> https://www.gatsbyjs.org/docs/gatsby-cli/#how-to-change-your-default-package-manager-for-your-next-project

Besides that, I investigated a little bit further about the issue of Contentful and found out that it's a well-known issue inside the package --> https://github.com/gatsbyjs/gatsby/issues/15397
The issue is still opened and there is no definitive solution yet ...

In the meantime, I manually set the version of `gatsby` and `gatsby-source-contentful` which will work with the starter when running `gatsby new`.

Please let me know if your issue is fixed so I can close this issue 😄

**Comment by fongaloid** [comment] 2019-12-18 06:53
Tested again and can confirm that it works! Thanks.

**Closed** 2019-12-18 07:16 UTC

**Comment by jung-youjin** [comment] 2020-03-17 09:04
Hi, I'm having the same issue as @fongaloid. I tried with `gatsby new` then `yarn start` and although the `package-lock.json` was there with me, but still got the same errors. I also tried by `git clone` your repository and ran with `npm start` but still got the same issue.

**Comment by SabirKhanAkash** [comment] 2022-03-28 07:33
> Hi, I'm having the same issue as @fongaloid. I tried with `gatsby new` then `yarn start` and although the `package-lock.json` was there with me, but still got the same errors. I also tried by `git clone` your repository and ran with `npm start` but still got the same issue.

Have you fixed your issue if so then how?
